---
services:
  mealie:
    image: ${MEALIE_IMAGE:-ghcr.io/mealie-recipes/mealie:v3.11.0}
    container_name: ${MEALIE_CONTAINER:-mealie}
    restart: unless-stopped
    ports:
      - "${MEALIE_PORT:-9925}:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: ${ALLOW_SIGNUP:-false}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/Chicago}
      #BASE_URL: https://mealie.yourdomain.com

volumes:
  mealie-data:
